name: CICD

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.PASSWORD_SAI }}" | docker login -u "${{ secrets.USERNAME_SAI }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t sainath521/tax-filing-frontend .

      - name: Publish image to Docker Hub
        run: docker push sainath521/tax-filing-frontend:latest   

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.229.92.87 << 'EOF'
            sudo bash -c "
              # Pull the latest Docker image
              docker pull sainath521/tax-filing-frontend:latest

              # Stop and remove the old Docker container if it exists
              docker rm -f taxFilingContainer || true

              # Run the new Docker container
              docker run -d -p 4000:4000 --name taxFilingContainer sainath521/tax-filing-frontend:latest
            "
          EOF